name: 'Optic Spec Viewer'
description: 'Automatically publish the latest spec of your API'
inputs:
  head:
    description: 'The branch to publish'
    required: true
    default: ${{ github.head_ref }}
  repository:
    description: 'The repo to look at' 
    required: true
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.head }}
branding:
  color: white
  icon: life-buoy