# action.yml
name: 'Optic Spec Viewer'
description: 'Automatically publish the latest spec of your API'
inputs:
  branch:
    description: 'The branch to publish'
    required: true
  repository:
    description: 'The repo to look at' 
    required: true
outputs:
  message: 
    description: 'The url where the spec is shared on'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}

