name: Deploy Spec Viewer / Pusher Site
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
      with:
          repository: trulyronak/gitbot
          branch: ${{ github.head_ref }}
          head: main
