name: Deploy Spec Viewer / Pusher Site
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # https://github.com/actions/checkout/commits/v2
      with:
        ref: ${{ github.head_ref }}
    - uses: ./
      with:
          repository: trulyronak/gitbot
          branch: ${{ github.head_ref }}
          head: main
      id: generate_spec
    - name: Comment on PR
      uses: unsplash/comment-on-pr@85a56be792d927ac4bfa2f4326607d38e80e6e60 # https://github.com/unsplash/comment-on-pr/commits/master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: ${{ steps.generate_spec.outputs.message }}
        check_for_duplicate_msg: false
