name: Deploy Spec Viewer / Pusher Site
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # https://github.com/actions/checkout/commits/v2
      with:
        ref: ${{ github.head_ref }}
    - uses: ./
      with:
          repository: trulyronak/gitbot
          branch: ${{ github.head_ref }}
          head: main
